version: 2

jobs:
  build_linux_c_compilergccfortran_compilergfortranmpimpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergccfortran_compilergfortranmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilergccfortran_compilergfortranmpiopenmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilergccfortran_compilergfortranmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_c_compilergccfortran_compilergfortranmpimpich
      - build_linux_c_compilergccfortran_compilergfortranmpiopenmpi
      - build_linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpich
      - build_linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpi
